### ISSUE TITLE
ants mass suicide

### ISSUE THREAD

**Issue by Musickiller** [segfaultdev/tree#5]
Hi!

My ants keep running into water and dying. Is that OK?)

Kind Regards,

**Comment by jmerono-saez** [comment]
Hey again! Yeah, that's expected due to how the code works, but obviously not ideal. This would require however writing a complex AI for ants, instead of the current "oooga booga let's just move to a random tile around us" one, which would slow down the game whenever high amounts of ants are present, so I don't think I'll do anything about it in the near future. Still, thanks!
